name: Laravel CD

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR ${{ secrets.AWS_REGION }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registries: '905418450006'
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Docker Login to ECR
      uses: docker/login-action@v3
      with:
        registry: ${{ steps.login-ecr.outputs.registry }}

    # - name: Build Image
    #   uses: docker/build-push-action@v5
    #   id: build-image
    #   with:
    #     context: .
    #     provenance: false
    #     file: ./Dockerfile
    #     push: true
    #     tags: ${{ github.sha }}
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max
    #     build-args: ''

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build .  -t warehouse-service
        docker tag warehouse-service:latest ${{ secrets.ECR_URL }}
        docker push ${{ secrets.ECR_URL }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 905418450006.dkr.ecr.us-east-2.amazonaws.com
          docker pull ${{ secrets.ECR_URL }}:latest
          docker stop warehouse-service || true
          docker rm warehouse-service || true
          docker run -p 80:80 -d --name warehouse-service \
            -e DB_CONNECTION=${{ secrets.DB_CONNECTION }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            ${{ secrets.ECR_URL }}:latest
          docker exec warehouse-service php artisan key:generate
